### ISSUE TITLE
Windows Support?

### ISSUE THREAD

**Issue by ItsJamie9494** [theCheeseboard/theBeat#3]
Some of your other projects (thePhoto and theSlate) now support Windows. Do you have any plans to get theBeat to Windows?

**Comment by vicr123** [comment]
I'd love to bring theBeat to Windows but unfortunately I can't find a working Phonon backend that works on Windows. It is definitely on the roadmap though :)

**Comment by vicr123** [comment]
Windows support is finally added! :D
